### ISSUE TITLE
Pop up menu is not clear

### ISSUE THREAD

**Issue by edgarkanyes** [bitcookies/pudding-vscode-theme#7]
When using **Pudding Light,** the text from the suggestions  menu is not clear. 

The screenshot below shows what I am referring to. (I am typing on line 35).
<img width="542" alt="Screenshot 2022-08-04 at 14 43 12" src="https://user-images.githubusercontent.com/75629102/182838920-8921f03e-7cf0-4ee7-a145-7ee9d3d7e8f9.png">

**Comment by bitcookies** [comment]
### Reply
Thank you very much for your feedback. 😀

The suggestions menu color is really not quite right and will be adjusted tomorrow. I will also check the other color issues in detail again tomorrow and release a new version later.

### A small survey 🗳
When using `Pudding Light Theme`, is the contrast between the color of the text and the background color obvious? Do I need to enhance the contrast between the text and the background?

![1](https://user-images.githubusercontent.com/18363796/182880723-0667fc9e-ddae-4df2-8f58-188cb02bac6f.jpg)

Thanks

**Comment by edgarkanyes** [comment]
Thanks for the quick response. Also, great work on the themes,
About the contrast on selecting a line, I turned off selected-line highlighting in my settings. I therefore may not be the right person to answer that.

**Comment by bitcookies** [comment]
`v2.0.2` has been updated. 😀

Some other issues of unclear text were also adjusted. For example `debugging foreground color`, `minimap color` and `hover background color`.

If you find other problems afterwards, please continue to give feedback.

Thanks brother
